### ISSUE TITLE
how to build it >?

### ISSUE THREAD

**Issue by xkk3599** [patrickelectric/SLAM_Qt#2]
i want to know how to build it ?And what does it depend?thanks

**Comment by patrickelectric** [comment]
Hi @xkk3599, you need Qt and Box2D installed.
After that you can run my examples with `qml main.qml` or `qmlscene main.qml`.
I'm working in a new backend to help me, and anybody else to use this projects, it's almost done and will be compiled, not interpreted by the qml machine.

**Comment by xkk3599** [comment]
thank you very much.

**Comment by patrickelectric** [comment]
There is new instructions, check the README.md
